(define (problem 2trackers-6plants)
(:domain killbee)
(:requirements)
(:objects 
  tr1 tr2  - tracker
  fum1  - fumigator
  h - hive
  p1 p2 p3 p4 p5 p6  - plant
)
(:init
  (first-plant tr1 p1)
  (directly-connected p1 p2)
  (directly-connected p1 p3)
  (directly-connected p1 h)
  (directly-connected p2 p1)
  (directly-connected p2 p3)
  (directly-connected p2 h)
  (directly-connected p3 p1)
  (directly-connected p3 p2)
  (directly-connected p3 h)
  (directly-connected h p1)
  (directly-connected h p2)
  (directly-connected h p3)
  (first-plant tr2 p4)
  (directly-connected p4 p5)
  (directly-connected p4 p6)
  (directly-connected p4 h)
  (directly-connected p5 p4)
  (directly-connected p5 p6)
  (directly-connected p5 h)
  (directly-connected p6 p4)
  (directly-connected p6 p5)
  (directly-connected p6 h)
  (directly-connected h p4)
  (directly-connected h p5)
  (directly-connected h p6)
  (at tr1 h)
  (tracker-ready-to-move tr1)
  (at tr2 h)
  (tracker-ready-to-move tr2)
  (at fum1 h)
)
(:goal   (and (at tr1 h)
  (at tr2 h)
  (at fum1 h)
  (plant-analyzed p1)
  (plant-analyzed p2)
  (plant-analyzed p3)
  (plant-analyzed p4)
  (plant-analyzed p5)
  (plant-analyzed p6)))
)